<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="AdminPage_Parham\images\" />
    <Folder Include="ChangeMenu_Parham\Images\" />
    <Folder Include="CustomerMainPage_Parham\Images\" />
    <Folder Include="ProfilePage_Parham\images\" />
    <Folder Include="RestaurantPanel_Parham\images\" />
  </ItemGroup>

</Project>
