<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="LoginForm_Matin\images\background1.jpg" />
    <None Remove="LoginForm_Matin\ToDo.txt" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="LoginForm_Matin\images\background1.jpg" />
  </ItemGroup>

</Project>
