<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AddRestunts_AdminPanel_Matin\**" />
    <Compile Remove="ReviewAndEditUnreviewedComplaints_Matin\**" />
    <Compile Remove="SigInPage_Matin\**" />
    <EmbeddedResource Remove="AddRestunts_AdminPanel_Matin\**" />
    <EmbeddedResource Remove="ReviewAndEditUnreviewedComplaints_Matin\**" />
    <EmbeddedResource Remove="SigInPage_Matin\**" />
    <None Remove="AddRestunts_AdminPanel_Matin\**" />
    <None Remove="ReviewAndEditUnreviewedComplaints_Matin\**" />
    <None Remove="SigInPage_Matin\**" />
    <Page Remove="AddRestunts_AdminPanel_Matin\**" />
    <Page Remove="ReviewAndEditUnreviewedComplaints_Matin\**" />
    <Page Remove="SigInPage_Matin\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Finish-forNow-DirectoryWrong\AddRestunts_AdminPanel_Matin\Images\woodBack.jpg" />
    <None Remove="Finish-forNow-DirectoryWrong\SetPassWordPage_Matin\images\hide.png" />
    <None Remove="Finish-forNow-DirectoryWrong\SetPassWordPage_Matin\images\lock_background.jpg" />
    <None Remove="Finish-forNow-DirectoryWrong\SetPassWordPage_Matin\images\show.png" />
    <None Remove="Finish-forNow-DirectoryWrong\SignInPage_Matin\images\backGround2.jpg" />
    <None Remove="Finish-forNow-DirectoryWrong\SignInPage_Matin\images\icons8-email-64.jpg" />
    <None Remove="Finish-forNow-DirectoryWrong\SignInPage_Matin\images\icons8-name-tag-64.jpg" />
    <None Remove="Finish-forNow-DirectoryWrong\SignInPage_Matin\images\icons8-phone-64.jpg" />
    <None Remove="Finish-forNow-DirectoryWrong\SignInPage_Matin\images\user.jpg" />
    <None Remove="Finish-forNow-DirectoryWrong\SignInPage_Matin\images\user.png" />
    <None Remove="Finish-forNow-DirectoryWrong\Search_complaints_PageADMIN_Matin\Images\s1.jpg" />
    <None Remove="Finish-forNow-DirectoryWrong\Search_complaints_PageADMIN_Matin\Images\s2.jpg" />
    <None Remove="Finish-forNow-DirectoryWrong\LoginForm_Matin\images\background1.jpg" />
    <None Remove="Finish-forNow-DirectoryWrong\LoginForm_Matin\images\res1.jpg" />
    <None Remove="Finish-forNow-DirectoryWrong\LoginForm_Matin\images\res2.jpg" />
    <None Remove="Finish-forNow-DirectoryWrong\OrderHistoryPage_Matin\Images\edit.png" />
    <None Remove="Finish-forNow-DirectoryWrong\OrderHistoryPage_Matin\Images\save.png" />
    <None Remove="Finish-forNow-DirectoryWrong\Follow_RegisterComplaints_Matin\Images\addIcon.png" />
    <None Remove="Finish-forNow-DirectoryWrong\Follow_RegisterComplaints_Matin\Images\addIcon_.png" />
    <None Remove="Finish-forNow-DirectoryWrong\Follow_RegisterComplaints_Matin\Images\edit.png" />
    <None Remove="Finish-forNow-DirectoryWrong\Follow_RegisterComplaints_Matin\Images\IconAdd_.png" />
    <None Remove="Finish-forNow-DirectoryWrong\Follow_RegisterComplaints_Matin\Images\save.png" />
    <None Remove="Review_Search_OrderAndReservation_ResturantsPanel_Matin\Images\s1.jpg" />
    <None Remove="Review_Search_OrderAndReservation_ResturantsPanel_Matin\Images\s2.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Finish-forNow-DirectoryWrong\AddRestunts_AdminPanel_Matin\Images\woodBack.jpg" />
    <Resource Include="Finish-forNow-DirectoryWrong\SetPassWordPage_Matin\images\hide.png" />
    <Resource Include="Finish-forNow-DirectoryWrong\SetPassWordPage_Matin\images\lock_background.jpg" />
    <Resource Include="Finish-forNow-DirectoryWrong\SetPassWordPage_Matin\images\show.png" />
    <Resource Include="Finish-forNow-DirectoryWrong\SignInPage_Matin\images\backGround2.jpg" />
    <Resource Include="Finish-forNow-DirectoryWrong\SignInPage_Matin\images\icons8-email-64.jpg" />
    <Resource Include="Finish-forNow-DirectoryWrong\SignInPage_Matin\images\icons8-name-tag-64.jpg" />
    <Resource Include="Finish-forNow-DirectoryWrong\SignInPage_Matin\images\icons8-phone-64.jpg" />
    <Resource Include="Finish-forNow-DirectoryWrong\SignInPage_Matin\images\user.jpg" />
    <Resource Include="Finish-forNow-DirectoryWrong\Search_complaints_PageADMIN_Matin\Images\s1.jpg" />
    <Resource Include="Finish-forNow-DirectoryWrong\Search_complaints_PageADMIN_Matin\Images\s2.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Finish-forNow-DirectoryWrong\LoginForm_Matin\images\background1.jpg" />
    <Resource Include="Finish-forNow-DirectoryWrong\LoginForm_Matin\images\res1.jpg" />
    <Resource Include="Finish-forNow-DirectoryWrong\LoginForm_Matin\images\res2.jpg" />
    <Resource Include="Finish-forNow-DirectoryWrong\OrderHistoryPage_Matin\Images\edit.png" />
    <Resource Include="Finish-forNow-DirectoryWrong\OrderHistoryPage_Matin\Images\save.png" />
    <Resource Include="Finish-forNow-DirectoryWrong\Follow_RegisterComplaints_Matin\Images\addIcon.png" />
    <Resource Include="Finish-forNow-DirectoryWrong\Follow_RegisterComplaints_Matin\Images\edit.png" />
    <Resource Include="Finish-forNow-DirectoryWrong\Follow_RegisterComplaints_Matin\Images\IconAdd_.png" />
    <Resource Include="Finish-forNow-DirectoryWrong\Follow_RegisterComplaints_Matin\Images\save.png" />
    <Resource Include="Review_Search_OrderAndReservation_ResturantsPanel_Matin\Images\s1.jpg" />
    <Resource Include="Review_Search_OrderAndReservation_ResturantsPanel_Matin\Images\s2.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="CSVtext\" />
  </ItemGroup>

</Project>
